/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ../public/haji.glb
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/haji.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[9.32, -0.06, 11.64]} scale={2.04}>
        <mesh geometry={nodes.Cube007.geometry} material={materials['Leather ornaments']} />
        <mesh geometry={nodes.Cube007_1.geometry} material={materials['Stainless Steel Clean']} />
        <mesh geometry={nodes.Cube007_2.geometry} material={materials['Car paint']} />
        <mesh geometry={nodes.Cube007_3.geometry} material={materials['Brazilian wood - Peroba Mica']} />
        <mesh geometry={nodes.Cube007_4.geometry} material={materials['Car windshield glass']} />
        <mesh geometry={nodes.Cube007_5.geometry} material={materials['Car plastic dark']} />
        <mesh geometry={nodes.Cube007_6.geometry} material={materials['Carlight shingle chrome red']} />
        <mesh geometry={nodes.Cube007_7.geometry} material={materials['Carlight shingle chrome orange']} />
        <mesh geometry={nodes.Cube007_8.geometry} material={materials.Mirror} />
        <mesh geometry={nodes.Cube007_9.geometry} material={materials['Car leather red']} />
        <mesh geometry={nodes.Cube007_10.geometry} material={materials['Car rubber wheel']} />
        <mesh geometry={nodes.Cube007_11.geometry} material={materials['Rusted steel']} />
        <mesh geometry={nodes.Cube013.geometry} material={materials['Stainless Steel Clean']} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials.FUEL} />
        <mesh geometry={nodes.Cube013_2.geometry} material={materials['FUEL CLOCK']} />
        <mesh geometry={nodes.Cube013_3.geometry} material={materials['FUEL OIL']} />
        <mesh geometry={nodes.Cube013_4.geometry} material={materials['FUEL 80']} />
        <mesh geometry={nodes.Cube013_5.geometry} material={materials['Car windshield glass']} />
        <mesh geometry={nodes.Cube013_6.geometry} material={materials['Plastic Shader']} />
        <mesh geometry={nodes.Cube013_7.geometry} material={materials['Black Plastic']} />
        <mesh geometry={nodes.Cube013_8.geometry} material={materials['Car plastic dark']} />
        <mesh geometry={nodes.Cube013_9.geometry} material={materials['Car paint']} />
        <mesh geometry={nodes.Cube013_10.geometry} material={materials['Car rubber wheel']} />
        <mesh geometry={nodes.Cube013_11.geometry} material={materials['Rusted steel']} />
        <mesh geometry={nodes.Plane005.geometry} material={materials['Car rubber wheel']} />
        <mesh geometry={nodes.Plane005_1.geometry} material={materials['Stainless Steel Clean']} />
        <mesh geometry={nodes['MG_Cars_(logo)'].geometry} material={materials['MG_Cars_(logo)']} />
        <mesh geometry={nodes['MG_Cars_(logo)_1'].geometry} material={materials['Stainless Steel Clean']} />
        <mesh geometry={nodes['MG_Cars_(logo)_2'].geometry} material={materials['Car plastic dark']} />
        <mesh geometry={nodes['MG_Cars_(logo)_3'].geometry} material={materials['Car paint']} />
        <mesh geometry={nodes['MG_Cars_(logo)_4'].geometry} material={materials.Sensore} />
        <mesh geometry={nodes['MG_Cars_(logo)_5'].geometry} material={materials['Car windshield glass']} />
        <mesh geometry={nodes['MG_Cars_(logo)_6'].geometry} material={materials.Speedometer} />
        <mesh geometry={nodes.Cube026.geometry} material={materials['Old Metal Pan']} />
        <mesh geometry={nodes.Cube026_1.geometry} material={materials['Car paint']} />
        <mesh geometry={nodes.Cube026_2.geometry} material={materials['Stainless Steel Clean']} />
        <mesh geometry={nodes.Plane.geometry} material={materials['Car rubber wheel']} />
        <mesh geometry={nodes.Plane_1.geometry} material={materials['Stainless Steel Clean']} />
        <mesh geometry={nodes.Cube003.geometry} material={materials['Stainless Steel Clean']} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Car rubber wheel']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials['Black Plastic']} />
        <mesh geometry={nodes.Cube003_3.geometry} material={materials['Car windshield glass']} />
      </group>
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={25.36} position={[-4.2, 0.97, 15.58]} rotation={[0.04, -0.59, 0.02]} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.010']} position={[-1.22, 2.32, 1.6]} rotation={[Math.PI / 2, 0, 0]} scale={[1.08, 0.64, 0.76]} />
      <mesh geometry={nodes.Text001.geometry} material={materials['Material.011']} position={[4.4, 1.25, 3.93]} rotation={[Math.PI / 2, 0, 0.71]} scale={[0.7, 0.42, 0.49]} />
      <group position={[-0.04, -0.03, -0.09]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube001_4.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube001_5.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube001_6.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube001_7.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube001_8.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube001_9.geometry} material={materials.ringhiera} />
        <mesh geometry={nodes.Cube001_10.geometry} material={materials['Material.009']} />
      </group>
      <mesh geometry={nodes.plate001.geometry} material={materials['porcelain white.005']} position={[3.97, 0.03, 4.38]} rotation={[Math.PI, 0, Math.PI]} scale={18.53}>
        <mesh geometry={nodes.coffee_bean015.geometry} material={materials['coffee bean']} position={[-0.03, 0.01, 0]} rotation={[-2.95, 1.55, 2.97]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean016.geometry} material={materials['coffee bean']} position={[-0.04, 0.01, 0]} rotation={[-3.06, -0.66, -3.1]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean019.geometry} material={materials['coffee bean']} position={[-0.03, 0.01, 0.03]} rotation={[2, 0.2, -1.4]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean029.geometry} material={materials['coffee bean']} position={[-0.01, 0.01, 0.02]} rotation={[-2.73, -1.43, -1.65]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean030.geometry} material={materials['coffee bean']} position={[-0.04, 0.01, 0.02]} rotation={[-0.05, 0.15, 2.79]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean031.geometry} material={materials['coffee bean']} position={[-0.03, 0.01, -0.01]} rotation={[2.92, 1.19, 0.2]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean032.geometry} material={materials['coffee bean']} position={[-0.02, 0.01, 0.02]} rotation={[1.15, 0.58, -0.51]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean033.geometry} material={materials['coffee bean']} position={[-0.05, 0.01, 0.01]} rotation={[-2.84, -0.73, 0.56]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean034.geometry} material={materials['coffee bean']} position={[-0.04, 0.01, 0.02]} rotation={[-2.47, -1.07, 1]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean035.geometry} material={materials['coffee bean']} position={[-0.02, 0.01, 0.02]} rotation={[-0.03, 0.97, -3.08]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean036.geometry} material={materials['coffee bean']} position={[-0.04, 0.01, 0.02]} rotation={[0.74, 1, 2.22]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean037.geometry} material={materials['coffee bean']} position={[-0.03, 0.01, 0.02]} rotation={[-0.83, -1.09, -1.84]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean038.geometry} material={materials['coffee bean']} position={[-0.02, 0.01, 0]} rotation={[-2.93, -0.88, -2.97]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean039.geometry} material={materials['coffee bean']} position={[-0.02, 0.01, 0.01]} rotation={[3.1, -1.39, -0.64]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean040.geometry} material={materials['coffee bean']} position={[-0.04, 0.01, 0.01]} rotation={[-2.95, -0.34, -2.68]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean041.geometry} material={materials['coffee bean']} position={[-0.04, 0.01, 0.01]} rotation={[-0.22, -1.14, 1.45]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean042.geometry} material={materials['coffee bean']} position={[-0.03, 0.01, 0.03]} rotation={[0.1, 0.13, -1.65]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean043.geometry} material={materials['coffee bean']} position={[-0.03, 0.01, -0.01]} rotation={[-0.17, -1.06, -0.18]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean044.geometry} material={materials['coffee bean']} position={[-0.03, 0.01, 0]} rotation={[0.26, 1.2, -0.15]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean045.geometry} material={materials['coffee bean']} position={[-0.04, 0.01, 0.01]} rotation={[-1.56, -0.96, -2.65]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean046.geometry} material={materials['coffee bean']} position={[-0.03, 0.01, 0.01]} rotation={[3.1, 0.02, -0.05]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean047.geometry} material={materials['coffee bean']} position={[-0.02, 0.01, 0.01]} rotation={[0.28, 1.45, -1.39]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean048.geometry} material={materials['coffee bean']} position={[-0.04, 0.01, 0]} rotation={[1.18, 1.12, 1.86]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean049.geometry} material={materials['coffee bean']} position={[-0.03, 0.01, 0.01]} rotation={[3.11, 0.62, -2.18]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean050.geometry} material={materials['coffee bean']} position={[-0.03, 0.01, 0]} rotation={[0.53, 0.08, 2.89]} scale={1.43} />
        <mesh geometry={nodes.coffee_bean051.geometry} material={materials['coffee bean']} position={[-0.02, 0.01, 0.01]} rotation={[0.18, 0.56, -1.61]} scale={1.43} />
        <mesh geometry={nodes.MUG001.geometry} material={materials['porcelain white.006']} position={[0, 0, -0.01]} rotation={[0, -1.57, 0]}>
          <mesh geometry={nodes.Circle001.geometry} material={materials['coffee.003']} position={[0, 0.05, 0]} scale={1.03} />
        </mesh>
        <mesh geometry={nodes.spoon001.geometry} material={materials['Iron Touched']} position={[0.02, 0.01, 0.02]} rotation={[-2.75, 1.31, 2.74]} scale={0.76} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/haji.glb')
